export const sidebarItems = [
  "Model 3",
  "Model S",
  "Model X",
  "Model Y",
  "Solar Roof",
  "Solar Panels",
  "Existing Inventory",
  "Used Inventory",
  "Trade-In",
  "Test Drive",
  "Powerwall",
  "Commercial Energy",
  "Utilities",
  "Charging",
  "Find Us",
  "Support",
  "Investor Relations",
  "Shop",
  "Account",
];
